object Versions {
    const val appcompat_version = "1.6.1"
    const val core_ktx_version = "1.13.1"
    const val constraintlayout_version = "2.1.4"
    const val material_version = "1.12.0"
    const val retrofit_version = "2.9.0"
    const val okhttp_version = "4.12.0"
    const val picasso_version = "2.71828"
    const val circleimageview_version = "3.0.0"
    const val room_version = "2.6.1"

    const val koin_version = "3.5.6"
    const val lifecycle_version = "2.5.1"
    const val coroutines_version = "1.6.0"

    const val junit4_version = "4.13.2"
    const val junit5_version = "5.10.0"
    const val mockk_version = "1.13.3"
    const val mockito_version = "2.27.0"
    const val mockito_kotlin_version = "2.1.0"
    const val core_testing_version = "2.1.0"
    const val core_ktx_test_version = "1.2.0"
    const val test_runner_version = "1.1.1"
    const val espresso_version = "3.1.1"
}